config/routes.rb
Rails.application.routes.draw do
  root 'websites#index'
  resources :websites
  resources :ethans
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ethan.rb
class Ethan < ApplicationRecord
    has_many :websites
end

app/models/website.rb
class Website < ApplicationRecord
    belongs_to :ethan
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ethans_controller.rb
class EthansController < ApplicationController
  before_action :set_ethan, only: [:show, :edit, :update, :destroy]

  # GET /ethans
  # GET /ethans.json
  def index
    @ethans = Ethan.all
  end

  # GET /ethans/1
  # GET /ethans/1.json
  def show
  end

  # GET /ethans/new
  def new
    @ethan = Ethan.new
  end

  # GET /ethans/1/edit
  def edit
  end

  # POST /ethans
  # POST /ethans.json
  def create
    @ethan = Ethan.new(ethan_params)

    respond_to do |format|
      if @ethan.save
        format.html { redirect_to @ethan, notice: 'Ethan was successfully created.' }
        format.json { render :show, status: :created, location: @ethan }
      else
        format.html { render :new }
        format.json { render json: @ethan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ethans/1
  # PATCH/PUT /ethans/1.json
  def update
    respond_to do |format|
      if @ethan.update(ethan_params)
        format.html { redirect_to @ethan, notice: 'Ethan was successfully updated.' }
        format.json { render :show, status: :ok, location: @ethan }
      else
        format.html { render :edit }
        format.json { render json: @ethan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ethans/1
  # DELETE /ethans/1.json
  def destroy
    @ethan.destroy
    respond_to do |format|
      format.html { redirect_to ethans_url, notice: 'Ethan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ethan
      @ethan = Ethan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ethan_params
      params.require(:ethan).permit(:login)
    end
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  before_action :set_website, only: [:show, :edit, :update, :destroy]

  # GET /websites
  # GET /websites.json
  def index
    @websites = Website.all
  end

  # GET /websites/1
  # GET /websites/1.json
  def show
  end

  # GET /websites/new
  def new
    @website = Website.new
  end

  # GET /websites/1/edit
  def edit
  end

  # POST /websites
  # POST /websites.json
  def create
    @website = Website.new(website_params)

    respond_to do |format|
      if @website.save
        format.html { redirect_to @website, notice: 'Website was successfully created.' }
        format.json { render :show, status: :created, location: @website }
      else
        format.html { render :new }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /websites/1
  # PATCH/PUT /websites/1.json
  def update
    respond_to do |format|
      if @website.update(website_params)
        format.html { redirect_to @website, notice: 'Website was successfully updated.' }
        format.json { render :show, status: :ok, location: @website }
      else
        format.html { render :edit }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /websites/1
  # DELETE /websites/1.json
  def destroy
    @website.destroy
    respond_to do |format|
      format.html { redirect_to websites_url, notice: 'Website was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_website
      @website = Website.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def website_params
      params.require(:website).permit(:url, :ethan_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ethans_helper.rb
module EthansHelper
end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/views/ethans/_form.html.erb
<%= form_with(model: ethan, local: true) do |form| %>
  <% if ethan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ethan.errors.count, "error") %> prohibited this ethan from being saved:</h2>

      <ul>
      <% ethan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :login %>
    <%= form.text_field :login %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ethans/edit.html.erb
<h1>Editing Ethan</h1>

<%= render 'form', ethan: @ethan %>

<%= link_to 'Show', @ethan %> |
<%= link_to 'Back', ethans_path %>

app/views/ethans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ethans</h1>

<table>
  <thead>
    <tr>
      <th>Login</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ethans.each do |ethan| %>
      <tr>
        <td><%= ethan.login %></td>
        <td><%= link_to 'Show', ethan %></td>
        <td><%= link_to 'Edit', edit_ethan_path(ethan) %></td>
        <td><%= link_to 'Destroy', ethan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ethan', new_ethan_path %>

app/views/ethans/new.html.erb
<h1>New Ethan</h1>

<%= render 'form', ethan: @ethan %>

<%= link_to 'Back', ethans_path %>

app/views/ethans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Login:</strong>
  <%= @ethan.login %>
</p>

<%= link_to 'Edit', edit_ethan_path(@ethan) %> |
<%= link_to 'Back', ethans_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hw3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/websites/_form.html.erb
<%= form_with(model: website, local: true) do |form| %>
  <% if website.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(website.errors.count, "error") %> prohibited this website from being saved:</h2>

      <ul>
      <% website.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_area :url %>
  </div>

  <div class="field">
    <%= form.label :ethan_id %>
    <%= form.number_field :ethan_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/websites/edit.html.erb
<h1>Editing Website</h1>

<%= render 'form', website: @website %>

<%= link_to 'Show', @website %> |
<%= link_to 'Back', websites_path %>

app/views/websites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Websites</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Ethan</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @websites.each do |website| %>
      <tr>
        <td><%= website.url %></td>
        <td><%= website.ethan_id %></td>
        <td><%= link_to 'Show', website %></td>
        <td><%= link_to 'Edit', edit_website_path(website) %></td>
        <td><%= link_to 'Destroy', website, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Website', new_website_path %>

app/views/websites/new.html.erb
<h1>New Website</h1>

<%= render 'form', website: @website %>

<%= link_to 'Back', websites_path %>

app/views/websites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @website.url %>
</p>

<p>
  <strong>Ethan:</strong>
  <%= @website.ethan_id %>
</p>

<%= link_to 'Edit', edit_website_path(@website) %> |
<%= link_to 'Back', websites_path %>